telovendo/home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.bienvenida, name='bienvenida'),
    path('mostrarUsuario', views.mostrarUsuario, name='mostrarUsuario')
]

telovendo/telovendo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

telovendo/home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Usuario(AbstractUser):

   
  username = models.CharField(max_length=50, null=False, unique=True)
  nombre = models.CharField(max_length=50,  null=True)
  apellido = models.CharField(max_length=50,  null=True)
  rut = models.CharField(max_length=50,  null=True)
  email = models.EmailField(max_length=254,  null=True,  unique=True)
  telefono = models.CharField(max_length=15)
  fecha_registro = models.DateTimeField(auto_now=False, auto_now_add=True)
  password = models.CharField(max_length=128, null=True)
  
  def save(self, *args, **kwargs):
    self.username = self.email  # Asignamos el valor del email al username
    super().save(*args, **kwargs)

# Create your models here.



    #OJO Agregar los modelos al admin !!!

telovendo/home/views.py
from django.shortcuts import render
from .models import Usuario



# Create your views here.

def bienvenida(request):
    return render(request, 'home/index.html', {
        } )

def mostrarUsuario(request):
    lista_usuario = Usuario.objects.all()
    return render(request, 'home/mostrar_usuario.html', {
        'lista_usuario' : lista_usuario
    })

telovendo/home/templates/home/index.html
{% extends 'home/layout/base.html' %}
{% block main %}
<head>
    <!-- Agrega aquí las etiquetas meta, los enlaces a CSS y otros elementos del head -->
    <style>
      /* Estilos para las tarjetas con tono pastel */
      .card-pastel {
        background-color: #f5e6e6; /* Cambia el color de fondo a un tono pastel */
        color: #555; /* Cambia el color del texto a un tono oscuro para que sea legible */
        border: none; /* Quita el borde de la tarjeta para hacerla más suave */
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Agrega una sombra para dar profundidad */
      }
  
      /* Estilos para el texto del footer */
      .footer-text {
        color: #fff; /* Cambia el color del texto del footer a blanco */
      }
      /* Estilos para el texto del footer */
        .footer-text {
            color: #fff; /* Cambia el color del texto del footer a blanco */
            text-align: center; /* Alinea el texto al centro */
            width: 100%; /* Establece el ancho del texto al 100% */
            margin: 0; /* Elimina el margen alrededor del texto */
            padding: 10px 0; /* Agrega un relleno vertical de 10px y 0 de relleno horizontal */
        }
    </style>
  </head>
  <body>
    <div class="container mt-5">
      <div class="row">
        <div class="col-sm-4">
          <!-- Contenido de la columna izquierda -->
          <!-- ... -->
        </div>
        <div class="col-sm-8">
          <!-- Testimonio 1 -->
          <div class="card card-pastel mt-3">
            <div class="card-body">
              <h5 class="card-title">¡Una experiencia increíble en "Te lo vendo"!</h5>
              <p class="card-text">¡Wow, simplemente wow! Mi primera compra en "Te lo vendo" fue una experiencia fantástica. La asesoría de moda en línea fue acertada, y estoy enamorada de cada prenda que compré. ¡Es como si hubieran leído mi mente y me presentaran exactamente lo que estaba buscando!</p>
              <p class="card-text"><small>Title description, Dic 7, 2022</small></p>
            </div>
          </div>
  
          <!-- Testimonio 2 -->
          <div class="card card-pastel mt-3">
            <div class="card-body">
              <h5 class="card-title">¡Amor a primera compra en "Te lo vendo"!</h5>
              <p class="card-text">¡Estoy encantado con mi compra en "Te lo vendo"! La asesoría de moda en línea fue excepcional, me ayudaron a encontrar exactamente lo que buscaba y descubrí algunas prendas que se adaptaban perfectamente a mi estilo. ¡El equipo de servicio al cliente fue amable y atento en todo momento!</p>
              <p class="card-text"><small>Title description, May 2, 2023</small></p>
            </div>
          </div>
  
          <!-- Puedes agregar más testimonios o contenido aquí usando el mismo formato de tarjeta -->
  
        </div>
      </div>
    </div>
  
  </body>

{% endblock main %}

telovendo/home/templates/home/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Te lo vendo</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href=" {% url 'home:bienvenida' %}" id="telovendo">Te lo Vendo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                    <a class="nav-link" href=" {% url 'home:mostrarUsuario' %} ">Mostrar Usuarios</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
            <div class= "row g-3">  
                 <div class="col-sm-10 col-md-10 col-lg-10 text-center">
                     <main>
                         {% block main %}
                         {% endblock main %}
                     </main>
                 </div>
             </div>
           
         </div>
    </main>
    <footer class="footer mt-5 py-3 bg-dark text-white text-center">
        <div class="container-fluid">
          <p class="footer-text">TE-LO-VENDO</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

telovendo/home/templates/home/mostrar_usuario.html
{% extends 'home/layout/base.html' %}
{% block main %}
    <div class="grid">
        <h2 class="card-title mt-4">Mostrando usuarios</h2>
        {% for user in lista_usuario %}
        <div class="card mb-4 mt-5" id="card1">
            <div class="row g-0">
                <div class="col-md-4">
                    <img 
                    src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxLDsbU94RA3B4A3dA3lkOVobdVm3i4-zlEw&usqp=CAU"
                    alt="usuario"
                    class="img-fluid rounded-start" />
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">Datos del Usuario</h5>
                        <p class="card-text"><td>{{ user.nombre }}</td></p>
                        <p class="card-text"><td>{{ user.apellido }}</td></p>
                        <p class="card-text"><td>{{ user.rut }}</td></p> 
                        <p class="card-text"><td>{{ user.email }}</td></p> 
                        <p class="card-text">
                            <small class="text-muted"><td>{{ user.fecha_registro }}</td></small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endfor %}
{% endblock main %}